spring.datasource.url=jdbc:postgresql://192.168.0.107:5432/budget_tracker
spring.datasource.username=postgres
spring.datasource.password=kaikai1296
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect