name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        run: ./mvnw clean package -DskipTests
        working-directory: budget-tracker-api

      - name: Copy JAR
        run: cp target/budget-tracker-api-0.0.1-SNAPSHOT.jar ~/budget-tracker-api-0.0.1-SNAPSHOT.jar
        working-directory: budget-tracker-api

      - name: Restart Service
        run: sudo systemctl restart budget-tracker-api
